name: CI/CD Pipeline MLOps

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    # Masukkan Secrets ke Environment Variable agar Script Python bisa baca
    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/submission-mlops.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install mlflow==2.19.0 dagshub scikit-learn pandas numpy matplotlib seaborn

    - name: Train Model & Log to DagsHub
      run: |
        python modelling_tuning.py

    # Ambil Run ID terbaru untuk keperluan Docker Build
    # Kita pakai script simple on-the-fly (tanpa file terpisah biar praktis)
    - name: Get Last Run ID
      id: get_run
      run: |
        run_id=$(python -c "import mlflow; mlflow.set_tracking_uri('${{ env.MLFLOW_TRACKING_URI }}'); runs = mlflow.search_runs(experiment_names=['Eksperimen_Loan_Prediction_Advance'], order_by=['start_time DESC'], max_results=1); print(runs.iloc[0].run_id)")
        echo "RUN_ID=$run_id" >> $GITHUB_ENV
        echo "Detected Run ID: $run_id"

    # Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker Image menggunakan MLflow
    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          --model-uri "runs:/${{ env.RUN_ID }}/model" \
          --name "${{ secrets.DOCKER_USERNAME }}/submission-mlops-model:latest" \
          --enable-mlserver

    # Push ke Docker Hub
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/submission-mlops-model:latest